# Setup
title:               Blog Padlan
tagline:             any stuff
url:                 http://fadhlanmr.github.io
analytics_id:        UA-53335201-2

# About/contact
author:
  name:                Fadhlan Min Robby
  email:               "fadhlan.mr@gmail.com" # email here 
  avatar:              img/avatar.jpg
  profile-pic:         img/profile-pic.jpg



# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: Fadhlan
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"
      